from: "data.yaml"


datasets:
  training:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/lsfb-cont/shards/annotated/shard_{000002..000007}.tar::/gpfs/scratch/acad/lsfb/datasets/dgs/shards/shard_{000000..000005}.tar"


experiment:
  variant: "lsfb_with_dgs"
