datasets:
  training:
    shards_url: "file:E:/datasets/sign-language/lsfb-isol/shards/500/shard_{000000..000003}.tar"
    loader:
      batch_size: 64
      shuffle: true
      num_workers: 0
    preprocessing:
      pose_transforms_pipeline: "concat+norm+temporal-crop+padding+flatten"

  validation:
    shards_url: "file:E:/datasets/sign-language/lsfb-isol/shards/500/shard_000004.tar"
    loader:
      batch_size: 64
      shuffle: False
      num_workers: 0
    preprocessing:
      pose_transforms_pipeline: "concat+norm+temporal-crop+padding+flatten"

  testing:
    shards_url: "file:E:/datasets/sign-language/lsfb-isol/shards/500/shard_000004.tar"
    loader:
      batch_size: 64
      shuffle: false
      num_workers: 0
    preprocessing:
      pose_transforms_pipeline: "concat+norm+temporal-crop+padding+flatten"

model:
  type: 'multi-head'
  backbone:
    type: 'spoter'
    args:
      n_classes: 500
      c_in: 130
      c_hidden: 128
      max_sequence_lengths: 64
      n_heads: 8
      n_encoder_layers: 6
      n_decoder_layers: 6
      dim_feedforward: 2048
      dropout: 0.1
  heads:
    classification:
      type: 'identity'
      in_channels: 500
      out_channels: 500

training:
  criterion:
    classification:
      name: "cross-entropy"
      use_weights: false
  max_epochs: 500
  early_stopping_patience: 30
  learning_rate: 1e-4
  is_output_multilayer: false
  n_classes: 500
  overfit_one_batch: false

experiment:
  id: "islr"
  suffix: "lsfb/lsfb500/debug"
  seed: 'random'
  output_dir: "D:/data/sign-languages/outs/slp2/isolated-recognition"
  mlflow_uri: "http://127.0.0.1:8142"
  show_progress_bar: true
  debug: false
