from: "base.yaml"

datasets:
  training:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/lsfb-cont/shards/annotated/shard_{000000..000005}.tar :: /gpfs/scratch/acad/lsfb/datasets/lsfb-cont/shards/annotated/shard_000007.tar"

  validation:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/lsfb-cont/shards/annotated/shard_000006.tar"

  testing:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/lsfb-cont/shards/annotated/shard_000006.tar"


experiment:
  id: "segmentation/lsfb"
  variant: "mstcn_off_fold6"
