from: "mstx_base.yaml"


experiment:
  variant: "mstx_2h_1s3b_h64_win128_rope"
  seed: random


model:
  name: 'hydra'
  backbone:
    name: 'ms-transformer'
    kwargs:
      in_channels: 130
      hidden_channels: 64
      max_length: 3200
      n_heads: 2
      dim_feedforward: 512
      n_stem_layers: 1
      n_branch_layers: 3
      dropout: 0.1
      pos_encoding: "rope"
      attn_mask_strategy: "window:128"
  neck:
    name: 'fpn'
    kwargs:
      c_in: 64
      c_out: 64
      n_levels: 6
      output_mode: "finest"
  channels_to_head_routing: "shared"
  heads:
    classification:
      name: "linear"
      n_channels: 64
      kwargs:
        in_features: 64
        out_features: 2
    regression:
      name: "linear"
      n_channels: 64
      kwargs:
        in_features: 64
        out_features: 2