datasets:
  training:
    shards_url: "file:E:/datasets/sign-language/lsa64/shards/shard_{000000..000004}.tar"
    loader:
      batch_size: 32
      shuffle: true
      num_workers: 0
    preprocessing:
      pose_transforms_pipeline: "concat+temporal-crop+norm+flatten"
  validation:
    shards_url: "file:E:/datasets/sign-language/lsa64/shards/shard_000004.tar"
    loader:
      batch_size: 32
      shuffle: false
      num_workers: 0
    preprocessing:
      pose_transforms_pipeline: "concat+temporal-crop+norm+flatten"
  testing:
    shards_url: "file:E:/datasets/sign-language/lsa64/shards/shard_000004.tar"
    loader:
      batch_size: 32
      shuffle: false
      num_workers: 0
    preprocessing:
      pose_transforms_pipeline: "concat+temporal-crop+norm+flatten"

model:
  name: "spoter"
  encoder:
    n_classes: 64,
    c_in: 130,
    max_sequence_lengths: 200,
    n_heads: 10,
    n_encoder_layers: 6,
    n_decoder_layers: 6,
    dim_feedforward: 2048,
    dropout: 0.1,
  heads:
    classification:
      in_channels: 64
      out_channels: 64
      layer: identity

training:
  criterion:
    classification:
      name: "cross-entropy"
      use_weights: false
  max_epochs: 300
  early_stopping_patience: 10
  learning_rate: 1e-4
  is_output_multilayer: false

experiment:
  id: "islr_example"
  suffix: "test"
  seed: 42
  output_dir: "D:/data/sign-languages/outs/slp2/isolated-recognition"
  show_progress_bar: true
  debug: true
