datasets:
  training:
    shards_url: "/home/sign-language/datasets/lsfb-cont/shards/shard_{000000..000003}.tar"
    loader:
      batch_size: 16
      shuffle: true
      num_workers: 23
    preprocessing:
      pose_transforms_pipeline: "concat+norm+flatten"
      use_windows: true
      window_size: 3500
      window_stride: 2800
      max_empty_windows: 0
      segment_codecs:
        - { name: 'actionness' }
  validation:
    shards_url: "/home/sign-language/datasets/lsfb-cont/shards/shard_000004.tar"
    loader:
      batch_size: 16
      shuffle: false
      num_workers: 23
    preprocessing:
      pose_transforms_pipeline: "concat+norm+flatten"
      use_windows: true
      window_size: 3500
      window_stride: 2800
      max_empty_windows: 0
      segment_codecs:
        - { name: 'actionness' }
  testing:
    shards_url: "/home/sign-language/datasets/lsfb-cont/shards/shard_000004.tar"
    loader:
      batch_size: 16
      shuffle: false
      num_workers: 23
    preprocessing:
      pose_transforms_pipeline: "concat+norm+flatten"
      use_windows: true
      window_size: 3500
      window_stride: 2800
      max_empty_windows: 0
      segment_codecs:
        - { name: 'actionness' }

model:
  type: 'multi-head'
  args:
    predict_on_all_stages: true
  backbone:
    type: 'mstcn'
    args:
      in_channels: 130
      out_channels: 2
      hidden_channels: 64
      n_stages: 4
      n_layers: 10
  heads:
    classification:
      type: 'identity'
      in_channels_range: [0, 2]

training:
  heads_to_targets:
    classification: frame_labels
  criterion:
    classification:
      name: "multi-layer+smoothing+cross-entropy"
      use_weights: true
  max_epochs: 300
  early_stopping_patience: 10
  learning_rate: 1e-4
  is_output_multilayer: true
  use_offsets: false
  segment_decoder: { name: 'actionness' }
  n_classes: 2

experiment:
  id: "segmentation"
  suffix: "actionness/lsfb/mstcn/weights"
  seed: 42
  output_dir: "/home/sign-language/outputs/segmentation"
  mlflow_uri: "http://127.0.0.1:8142"
  show_progress_bar: true
  debug: false
