from: "lsfb_actionness_mstcn.yaml"

datasets:
  training:
    preprocessing:
      segment_codecs:
        - { name: 'actionness' }
        - { name: 'offsets' }
  validation:
    preprocessing:
      segment_codecs:
        - { name: 'actionness' }
        - { name: 'offsets' }
  testing:
    preprocessing:
      segment_codecs:
        - { name: 'actionness' }
        - { name: 'offsets' }

model:
  backbone:
    type: 'mstcn'
    args:
      out_channels: 4
  heads:
    regression:
      type: 'identity'
      in_channels_range: [2, 4]

training:
  heads_to_targets:
    regression: offsets
  criterion:
    regression:
      name: "multi-layer+gIoU"
  use_offsets: true
  segment_decoder: { name: 'offsets' }


experiment:
  id: "segmentation"
  suffix: "offsets/lsfb/mstcn/noweight"
  debug: false
