from: "1.actionness_with_weights.yaml"

id: "bio_tagging_with_weights"

datasets:
  training:
    preprocessing:
      segment_codecs:
        - { name: 'bio_tags', args: { b_tag_size: 0.1 } }
  validation:
    preprocessing:
      segment_codecs:
        - { name: 'bio_tags', args: { b_tag_size: 0.1 } }
  testing:
    preprocessing:
      segment_codecs:
        - { name: 'bio_tags', args: { b_tag_size: 0.1 } }

backbone:
  module_kwargs:
    out_channels: 3

training:
  criterion:
    n_classes: 3
    use_weights: true

target_codec:
  name: "bio_tags"
  args: { b_tag_size: 2 }
  use_offsets: false
