from: "io.yaml"


experiment:
  variant: "mstcn_io_weight_inverse"
  seed: random


training:
  loss_functions:
    classification:
      name: "cross-entropy"
      use_weights: true
      weight_strategy: "inverse"
      multi_layer: true