from: "actionness.yaml"

id: "phoenix_boundaries_without_weights"

datasets:
  training:
    preprocessing:
      segment_codecs:
        - { name: 'boundaries' }
  validation:
    preprocessing:
      segment_codecs:
        - { name: 'boundaries' }
  testing:
    preprocessing:
      segment_codecs:
        - { name: 'boundaries' }

training:
  criterion:
    use_weights: false

target_codec:
  name: "boundaries"
  use_offsets: false
