from: "3.actionness_with_offsets_and_weights.yaml"


experiment:
  variant: "mstcn_off_weight_sqrt"
  seed: random


training:
  loss_functions:
    classification:
      name: "cross-entropy"
      use_weights: true
      weight_strategy: "inverse_sqrt"
      multi_layer: true
    regression:
      name: "gIoU"
      use_weights: false
      multi_layer: true
