from: "base.yaml"

datasets:
  training:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/dgs/shards/shard_000000.tar::/gpfs/scratch/acad/lsfb/datasets/dgs/shards/shard_{000002..000007}.tar"

  validation:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/dgs/shards/shard_000001.tar"

  testing:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/dgs/shards/shard_000001.tar"


experiment:
  variant: "mstcn_off_fold1"
