from: "bound_off.yaml"


experiment:
  variant: "bound_off_weights_2"
  seed: random


training:
  loss_functions:
    classification:
      name: "cross-entropy"
      use_weights: true
      weight_strategy: "inverse"
      multi_layer: true
    regression:
      name: "gIoU"
      use_weights: false
      multi_layer: true
