from: "vit_base.yaml"


experiment:
  variant: "vit_6h_7l_h384_win128_rope"
  seed: random


model:
  name: 'hydra'
  backbone:
    name: 'vit'
    kwargs:
      in_channels: 130
      hidden_channels: 384
      max_length: 3200
      n_heads: 6
      n_layers: 7
      dim_feedforward: 1536
      dropout: 0.1
      pos_encoding: "rope"
      attn_mask_strategy: "window:128"
  channels_to_head_routing: "shared"
  heads:
    classification:
      name: "linear"
      n_channels: 384
      kwargs:
        in_features: 384
        out_features: 2
    regression:
      name: "linear"
      n_channels: 384
      kwargs:
        in_features: 384
        out_features: 2