from: "data_lsfb.yaml"


experiment:
  variant: "resnet50"
  seed: random


model:
  name: 'hydra'
  backbone:
    name: 'resnet2d'
    kwargs:
      num_layers: 50
      pretrained: false
  channels_to_head_routing: "shared"
  heads:
    classification:
      name: "linear"
      n_channels: 2048
      kwargs:
        in_features: 2048
        out_features: 500


training:
  max_epochs: 150

  loss_functions:
    classification:
      name: "cross-entropy"
      use_weights: false
      multi_layer: false

  learning_rate: 1.0e-4
  early_stopping_patience: 20
#  lr_scheduler:
#    name: 'warmup-plateau-cosine-annealing'
#    kwargs:
#      n_warmup_steps: 10
#      n_plateau_steps: 0
#      max_steps: 150
#      lr: 1.0e-4
#      start_lr: 1.0e-6
#      end_lr: 1.0e-6

  n_classes: 2

  is_output_multistage: true
  overfit_one_batch: false

  heads_to_targets:
    classification: temporal-segmentation
