from: "7.boundaries_with_weights.yaml"

id: "boundaries_with_offsets_and_weights"

datasets:
  training:
    preprocessing:
      segment_codecs:
        - { name: 'boundaries+offsets' }
  validation:
    preprocessing:
      segment_codecs:
        - { name: 'boundaries+offsets' }
  testing:
    preprocessing:
      segment_codecs:
        - { name: 'boundaries+offsets' }

target_codec:
  name: "boundaries+offsets"
  use_offsets: true

backbone:
  module_kwargs:
    out_channels: 4 # 2 labels (background + signing) and 2 offsets (start + end)

training:
  criterion:
    name: "multi-layer+ce+smoothing+offsets"
