datasets:
  training:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/lsfb-cont/shards/annotated/shard_{000002..000007}.tar"
    pose_body_parts: ["upper_pose", "left_hand", "right_hand", "lips"]
    dataloader:
      batch_size: 32
      shuffle: true
      n_workers: 2
    preprocessing:
      targets:
        - 'temporal-segmentation'
        - 'temporal-offsets'
        - 'segments'
      pose_transforms:
        - {
          name: 'norm+flatten2d',
          kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ] }
        }
      use_windows: true
      window_size: 3200
      window_stride: 2560
      max_empty_windows: 0

  validation:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/lsfb-cont/shards/annotated/shard_000001.tar"
    pose_body_parts: ["upper_pose", "left_hand", "right_hand", "lips"]
    dataloader:
      batch_size: 32
      shuffle: false
      n_workers: 2
    preprocessing:
      targets:
        - 'temporal-segmentation'
        - 'temporal-offsets'
        - 'segments'
      pose_transforms:
        - {
          name: 'norm+flatten2d',
          kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ] }
        }
      use_windows: true
      window_size: 3200
      window_stride: 2560
      max_empty_windows: 0

  testing:
    shards_url: "/gpfs/scratch/acad/lsfb/datasets/lsfb-cont/shards/annotated/shard_000000.tar"
    pose_body_parts: ["upper_pose", "left_hand", "right_hand", "lips"]
    dataloader:
      batch_size: 32
      shuffle: false
      n_workers: 2
    preprocessing:
      targets:
        - 'temporal-segmentation'
        - 'temporal-offsets'
        - 'segments'
      pose_transforms:
        - {
          name: 'norm+flatten2d',
          kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ] }
        }
      use_windows: true
      window_size: 3200
      window_stride: 2560
      max_empty_windows: 0


experiment:
  id: "segmentation/14-pose-settings/lsfb"
  output_dir: "/gpfs/scratch/acad/lsfb/outputs/hydra_v2"
  debug: false
  show_progress_bar: false