from: "base.yaml"


experiment:
  variant: "mstcn_medium/poses_s03_hands+up+lips"
  seed: random


datasets:
  training:
    pose_body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ]
    preprocessing:
      pose_transforms:
        - {
          name: 'norm+flatten2d',
          kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ] }
        }

  validation:
    pose_body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ]
    preprocessing:
      pose_transforms:
        - {
          name: 'norm+flatten2d',
          kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ] }
        }

  testing:
    pose_body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ]
    preprocessing:
      pose_transforms:
        - {
          name: 'norm+flatten2d',
          kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips" ] }
        }


model:
  name: 'hydra'
  backbone:
    name: "ms-tcn"
    kwargs:
      in_channels: 210 # = upper_body + left/right_hand + lips (105 x 2d)
      out_channels: 4
      hidden_channels: 64
      n_stages: 4
      n_layers: 10
  heads:
    classification:
      name: "identity"
      n_channels: 2
    regression:
      name: "identity"
      n_channels: 2
