from: "base.yaml"


experiment:
  variant: "mstcn_medium/poses_s04_hands+up+lips+eyes"
  seed: random


datasets:
  training:
    pose_body_parts: [ "upper_pose", "left_hand", "right_hand", "lips", "left_eye", "left_iris", "right_eye", "right_iris" ]
    preprocessing:
      pose_transforms:
        - { name: 'norm+flatten2d',
            kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips", "left_eye", "left_iris", "right_eye", "right_iris" ] } }

  validation:
    pose_body_parts: [ "upper_pose", "left_hand", "right_hand", "lips", "left_eye", "left_iris", "right_eye", "right_iris" ]
    preprocessing:
      pose_transforms:
        - { name: 'norm+flatten2d',
            kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips", "left_eye", "left_iris", "right_eye", "right_iris" ] } }

  testing:
    pose_body_parts: [ "upper_pose", "left_hand", "right_hand", "lips", "left_eye", "left_iris", "right_eye", "right_iris" ]
    preprocessing:
      pose_transforms:
        - { name: 'norm+flatten2d',
            kwargs: { body_parts: [ "upper_pose", "left_hand", "right_hand", "lips", "left_eye", "left_iris", "right_eye", "right_iris" ] } }


model:
  name: 'hydra'
  backbone:
    name: "ms-tcn"
    kwargs:
      in_channels: 290 # = upper_body + hands + lips + eyes (145 x 2d)
      out_channels: 4
      hidden_channels: 64
      n_stages: 4
      n_layers: 10
  heads:
    classification:
      name: "identity"
      n_channels: 2
    regression:
      name: "identity"
      n_channels: 2
