datasets:
  training:
    shards_url: "file:F:/datasets/sign-language/lsfb-cont/shards/annotated/shard_{000002..000007}.tar"
    dataloader:
      batch_size: 16
      shuffle: true
      n_workers: 23
    preprocessing:
      targets: [ 'temporal-segmentation', 'temporal-offsets', 'segments' ]
      pose_transforms: [ { name: 'norm+flatten2d' } ]
      use_windows: true
      window_size: 3500
      window_stride: 2800
      max_empty_windows: 0

  validation:
    shards_url: "file:F:/datasets/sign-language/lsfb-cont/shards/annotated/shard_000001.tar"
    dataloader:
      batch_size: 16
      shuffle: false
      n_workers: 23
    preprocessing:
      targets: [ 'temporal-segmentation', 'temporal-offsets', 'segments' ]
      pose_transforms: [ { name: 'norm+flatten2d' } ]
      use_windows: true
      window_size: 3500
      window_stride: 2800
      max_empty_windows: 0

  testing:
    shards_url: "file:F:/datasets/sign-language/lsfb-cont/shards/annotated/shard_000000.tar"
    dataloader:
      batch_size: 16
      shuffle: false
      n_workers: 23
    preprocessing:
      targets: [ 'temporal-segmentation', 'temporal-offsets', 'segments' ]
      pose_transforms: [ { name: 'norm+flatten2d' } ]
      use_windows: true
      window_size: 3500
      window_stride: 2800
      max_empty_windows: 0


experiment:
  id: "segmentation/lsfb"
  output_dir: "F:/outputs/segmentation/archs"
  debug: false
  show_progress_bar: true