from: "transformer_01.yaml"


experiment:
  variant: "vit_4h_6l_512"
  seed: random


model:
  name: 'hydra'
  backbone:
    name: 'vit'
    kwargs:
      in_channels: 130
      hidden_channels: 512
      max_length: 300
      n_heads: 4
      n_layers: 6
      dim_feedforward: 1024
      dropout: 0.1
      pos_encoding: "rope"
      attn_mask_strategy: "window:128"
  heads:
    classification:
      name: "linear"
      n_channels: 256
      kwargs:
        in_features: 256
        out_features: 2
    regression:
      name: "linear"
      n_channels: 256
      kwargs:
        in_features: 256
        out_features: 2
